export const PASSAGES: readonly string[] = [
  "The quick brown fox jumps over the lazy dog every morning.",
  "Pack my box with five dozen liquor jugs before the trip.",
  "How vexingly quick daft zebras jump across the field.",
  "Sphinx of black quartz, judge my vow without delay.",
  "The five boxing wizards jump quickly over the bench.",
  "Bright vixens jump for the lazy fowl every single day.",
  "A wizard's job is to vex chumps quickly in the fog.",
  "Waltz, bad nymph, for quick jigs vex the calm dog.",
  "Honey bees can flap their wings two hundred times a second.",
  "The Eiffel Tower grows taller by several centimetres in summer.",
  "Octopuses have three hearts and blue copper-based blood.",
  "A group of flamingos is fittingly known as a flamboyance.",
  "Light from the sun takes about eight minutes to reach us.",
  "The shortest war in history lasted under forty minutes.",
  "Wombats produce neat little cube-shaped droppings overnight.",
  "Bananas are mildly radioactive thanks to their potassium.",
  "A single bolt of lightning is hotter than the sun's surface.",
  "Sharks existed long before the very first trees grew.",
  "The human nose can recognise over a trillion distinct scents.",
  "Sea otters hold hands while sleeping so they do not drift.",
  "Venus is the only planet that spins clockwise on its axis.",
  "A teaspoon of neutron star would weigh billions of tonnes.",
  "Cats cannot taste anything that happens to be sweet.",
  "The Great Wall of China is not visible from low orbit.",
  "Penguins propose to their mates with a carefully chosen pebble.",
  "Some turtles can breathe through their hind quarters underwater.",
  "An ostrich's eye is bigger than its surprisingly small brain.",
  "Hot water can sometimes freeze faster than cold water does.",
  "The dot over a lowercase letter i is called a tittle.",
  "A crocodile cannot stick its tongue out of its mouth.",
  "Be the change that you wish to see in the world today.",
  "The only way to do great work is to love what you do.",
  "In the middle of difficulty lies a surprising opportunity.",
  "It always seems impossible until the moment it is finally done.",
  "What we think, we become, one quiet thought at a time.",
  "The journey of a thousand miles begins with a single step.",
  "Happiness depends upon ourselves more than upon our luck.",
  "Knowing yourself is the true beginning of all wisdom.",
  "A room without books is like a body without a soul.",
  "We are what we repeatedly do, so excellence is a habit.",
  "Courage is grace performed under a great deal of pressure.",
  "Not all those who wander are necessarily lost on the way.",
  "The future belongs to those who believe in their dreams.",
  "Do what you can, with what you have, where you are now.",
  "Simplicity is the ultimate form of true sophistication.",
  "A smooth sea has never made a genuinely skilful sailor.",
  "The early bird may get the worm, but the cat sleeps in.",
  "Every storm runs out of rain sooner or later, they say.",
  "Stars cannot shine at all without a little bit of darkness.",
  "Whether you think you can or cannot, you are quite right.",
  "Type as fast as you can without sacrificing your accuracy.",
  "Steady fingers and a calm mind beat a frantic clatter.",
  "Reading widely is the surest path to writing clearly.",
  "Coffee first, then the rest of the day can sort itself out.",
  "A clever programmer writes code that humans can read.",
  "Patience and persistence quietly conquer almost everything.",
  "The best time to plant a tree was twenty years ago.",
  "Practice makes progress, even when it does not make perfect.",
  "Kind words can be short, yet their echoes are endless.",
  "Good things come to those who wait and keep on trying.",
  "Music is the silence between the notes more than the notes.",
  "The grass is greener where you actually choose to water it.",
  "Curiosity is the engine that drives every great discovery.",
];
