export const SECRETS: readonly string[] = [
  "river", "mountain", "garden", "window", "candle", "bridge", "forest", "island",
  "harbour", "valley", "meadow", "thunder", "winter", "summer", "morning", "evening",
  "shadow", "mirror", "feather", "diamond", "silver", "copper", "marble", "velvet",
  "anchor", "compass", "lantern", "harvest", "blossom", "cottage", "castle",
  "library", "kitchen", "ceiling", "balcony", "chimney", "fountain", "orchard", "pasture",
  "wander", "gather", "whisper", "tremble", "scatter", "ponder", "linger", "flourish",
  "engine", "rocket", "planet", "comet", "galaxy", "gravity", "magnet", "circuit",
  "doctor", "farmer", "painter", "sailor", "soldier", "teacher", "builder", "hunter",
  "ladder", "hammer", "needle", "ribbon", "basket", "bottle", "pillow", "blanket",
  "tunnel", "highway", "station", "village", "factory", "market", "theatre",
  "puppy", "kitten", "rabbit", "monkey", "tiger", "eagle", "dolphin", "spider",
  "honey", "pepper", "butter", "cherry", "lemon", "ginger", "almond", "walnut",
  "guitar", "violin", "trumpet", "drummer", "melody", "rhythm", "chorus", "anthem",
  "battle", "treaty", "empire", "throne", "knight", "wizard", "dragon", "legend",
  "memory", "dream", "wonder", "courage", "patience", "freedom", "promise", "secret",
  "frozen", "molten", "rugged", "gentle", "fierce", "humble", "clever", "graceful",
  "puzzle", "riddle", "mystery", "journey", "voyage", "summit", "horizon", "ocean",
];
